A = [64, 34, 25, 12, 22, 11, 90]
print("Arreglo :", A)
A.sort()
print("Arreglo ordenado:", A)
A.sort(reverse=True)
print("Arreglo ordenado:", A)
colors = ['Red', 'Green', 'Orange', 'Pink']
print("lista de colores:")
print(colors)
colors.sort()
print('\nOrden ascendente:')
print(colors)
print('\nOrden descendente:')
colors.sort(reverse=True)
print(colors)
